### ISSUE TITLE
Config file should be merged with default config

### ISSUE THREAD

**Issue by hitochan777** [shirasudon/go-chat#31]
When I set custom config in which some settings are commented out, the commented out settings are out complemented with the default values.

For example, when I use the following config, I expected the server to return `index.html` as a response to the request to `/index.html`. However, since `EnableServestaticFile` is not set to the default value ( which is `true`), static files are not served. I think this behavior is a bit counter-intuitive. Could you please set settings that are not set in the config file to the default values? 
```toml
HTTP = "localhost:8080"
# ChatAPIPrefix = ""
# StaticHandlerPrefix = ""
StaticFileDir = "public"
# EnableServeStaticFile = true
# ShowRoutes = true
```
